# 使用github actions监听dev分支push
# 登陆测试机 获取dev最新代码
# 重新构建镜像 docker-compose build lego-web-server
# 重启所有容器 docker-compose up -d

name: deploy for dev

on:
    push:
          branches:
              - 'dev' # 只针对 dev 分支
          paths:
              - '.github/workflows/*'
              # - '__test__/**' # dev 不需要立即测试
              - 'src/**'
              - 'Dockerfile'
              - 'docker-compose.yml'
              - 'bin/*'
jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.LLX_ID_RSA_PUB}}" > ~/.ssh/id_rsa.pub
                  chmod 600 ~/.ssh/id_rsa.pub
                  ssh-copy-id -i ~/.ssh/id_rsa.pub work@116.85.16.44
                  ssh-keyscan "116.85.16.44" >> ~/.ssh/known_hosts
            - name: deploy
              run: |
                  ssh work@116.85.16.44
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa