# 使用github actions监听dev分支push
# 登陆测试机 获取dev最新代码
# 重新构建镜像 docker-compose build lego-web-server
# 重启所有容器 docker-compose up -d

name: deploy for dev

on:
    push:
          branches:
              - 'dev' # 只针对 dev 分支
          paths:
              - '.github/workflows/*'
              # - '__test__/**' # dev 不需要立即测试
              - 'src/**'
              - 'Dockerfile'
              - 'docker-compose.yml'
              - 'bin/*'
jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.LLX_ID_RSA}}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "116.85.16.44" >> ~/.ssh/known_hosts
            - name: deploy
              run: |
                  ssh work@116.85.16.44 "
                    # 【注意】用 work 账号登录，手动创建 /home/work/lego-web 目录
                    # 然后 git clone https://username:password@github.com/imooc-lego/biz-editor-server.git -b dev （私有仓库，使用 github 用户名和密码）
                    # 记得删除 origin ，否则会暴露 github 密码 因为clone时候带了密码 git remote -v可查看信息

                    cd /home/work/lego-web/lego-web-server;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa